### PR TITLE
Custom tagging of services

### PR DESCRIPTION
**Pull request by mwl**
Parse up a `"HUMIO_TAG_foo": "bar"` as `foo:bar` field

### CODE REVIEW

**Comment by mwl** [comment]
@blublinsky Not entirely sure what you mean. Some way to tag tasks that aren't created by Marathon? I've done a little bit of that for marathon-lb and I'd like to add more.

**Comment by blublinsky** [comment]
Hi Martin, what I mean is allowing to add a set of custom labels to the marathon definition and propagate them to the log.
Here is an example - lets say I have 2 services A and B, which are part of a bigger application C.
What I want is to add label c to both services, so that I can bring their logs together

**Comment by mwl** [comment]
But isn't that exactly what this PR does?
If you add the label `"HUMIO_FIELD_customer": "AcmeCorp"`, all logs will have the `customer="AcmeCorp"` field on them.

**Comment by blublinsky** [comment]
Yes, my bad

**Pull request merged**
